<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-4">
                        <img src="<?= $this->url->get('img/logo.png') ?>" alt="" class="img img-thumbnail">
                    </div>
                    <div class="col-lg-4">
                        <img src="<?= $this->url->get('img/foto.JPG') ?>" alt="" class="img img-thumbnail">
                    </div>
                    <div class="col-lg-4">
                        <img src="<?= $this->url->get('img/kppn.JPG') ?>" alt="" class="img img-thumbnail">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#memberModal').modal('show');

    });
</script>